project:
  type: website
  output-dir: docs/
  render:
    - "*.qmd"
    - "!presentation/"

website:
  title: "AITI Talk"
  repo-url: https://github.com/haziqj/aiti-talk
  issue-url: https://github.com/haziqj/aiti-talk/issues
  repo-actions: [edit, issue]

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://github.com/haziqj/aiti-talk
        text: Material
      - href: https://haziqj.ml/aiti-talk/presentation
        text: Slides
      - href: R/report.qmd
        text: Report

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


lightbox: true


